### ISSUE TITLE
use data-themes attribute instead of class on html tag

### ISSUE THREAD

**Issue by revelt** [abereghici/remix-themes#10]
### Describe the bug

Currently, we set a `class` on `html` tag, which works, but is not a good practice.

What if we used `data-theme` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) instead?

```jsx
<html data-theme="dark">
```

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

n/a

### Expected behavior

n/a

### Platform

all

**Comment by abereghici** [comment]
Hey @revelt, thanks for opening this issue and for your feedback. I updated the demo app and the README to use data attribute instead of className.

**Comment by revelt** [comment]
@abereghici  Awesome! Thank you! It's very solid, works as promised. I only see the theme state being reset on Safari, but that's probably its privacy-related safeguards. Theoretically, if we decide to look into it, we should look into ways to supplement the cookie-sessions with localstorage backup, to nail Safari. Other than that, all super!

**Comment by abereghici** [comment]
@revelt I just created a new issue to investigate the Safari issue.
