### ISSUE TITLE
The theme state being reset on Safari, might be related to its privacy-related safeguards

### ISSUE THREAD

**Issue by abereghici** [abereghici/remix-themes#11]
@abereghici  The theme state being reset on Safari, but that's probably its privacy-related safeguards. Theoretically, if we decide to look into it, we should look into ways to supplement the cookie-sessions with localstorage backup, to nail Safari. 

_Originally posted by @revelt in https://github.com/abereghici/remix-themes/issues/10#issuecomment-1162944508_

**Comment by abereghici** [comment]
Safari might not store the cookie if the `domain` property is not set or the `secure` flag is activated on localhost ( it should be activated for the production (SSL) environment). I updated the demo application and now it's working fine on Safari.

**Comment by revelt** [comment]
Good work!
