### ISSUE TITLE
Remix 2.0.0 support

### ISSUE THREAD

**Issue by Fireclunge** [abereghici/remix-themes#23]
### Describe the bug

Remix v2.0.0 not supported

### Your Example Website or App

penisland.com

### Steps to Reproduce the Bug or Issue

upgrade your remix project to version 2.0.0 while using remix-themes

### Expected behavior

I would expect the library to work as in 1.19.X without having to use dependancy workarounds

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by abereghici** [comment]
@Fireclunge thanks
