### ISSUE TITLE
Button with transition-colors applied flashing when toggling mode tailwind

### ISSUE THREAD

**Issue by skydistefanof** [abereghici/remix-themes#26]
### Describe the bug

I found a problem that, when switching theme, all elements that have a transition color on them will flash.
The solution of removing the transition color on all elements is not applicabile for stylistic reasons
Will open a pr to fix this

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1. Setup a remix project with tailwind
2. Add a transition color to any element
3. Watch the flashing 

### Expected behavior

I expect no strange flashing even with transition applied

### Screenshots or Videos

https://github.com/abereghici/remix-themes/assets/134290176/a70e6c0d-da83-4c40-b50e-e85d0b1eb80f

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [121.0]

**Comment by abereghici** [comment]
https://github.com/abereghici/remix-themes/releases/tag/v1.3.0
