### ISSUE TITLE
Allow a 'System' setting as an option

### ISSUE THREAD

**Issue by abereghici** [abereghici/remix-themes#33]
### Discussed in https://github.com/abereghici/remix-themes/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **micotodev** March 29, 2023</sup>
A lot of websites have Light/Dark and then a 'System' preference (see [Tailwind CSS website](https://tailwindcss.com/)).

Currently, if the user has chosen a specific colour theme on the website, it will be changed irrespective of their choice when they change their system preference.

Maybe having an extra flag of `isSystemPreference: boolean` and only set the event listener when that is true would be the best option. We could still set the Theme enum (but with the ability to check for this flag when creating a dropdown of the three values).</div>

**Comment by glassworks-projects** [comment]
+1 :)

**Comment by abereghici** [comment]
https://github.com/abereghici/remix-themes/releases/tag/v1.4.0
